### ISSUE TITLE
关于日历的可否加上圣诞节教师节等节日

### ISSUE THREAD

**Issue by enjoyinglove** [vsme/vsme#1]
您好，关于日历的建议可否加上圣诞节教师节等节日

**Comment by vsme** [comment]
这些节日在阳历中的日期比较固定，直接获取月份和日期就好了，比如 教师节是9月10日，圣诞节永远是12月25，这不像阴历节日那样不固定，暂不考虑加入。

**Comment by vsme** [comment]
https://github.com/vsme/chinese-days/issues/8
